import chalk from "chalk";
import { existsSync, writeFileSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { findRepoRoot, NotAGitRepoError } from "../utils/repoRoot.js";
import { dbPath, configPath, reportsDir } from "../utils/paths.js";
import { getPrisma, closePrisma } from "../db/client.js";
import { getRepository } from "../db/queries.js";
import { generateReleaseNotes } from "../releasenotes/index.js";
import { spinner } from "../utils/spinner.js";

export async function releaseCommand(fromRef: string, toRef: string, dir?: string): Promise<void> {
  const targetDir = dir ?? process.cwd();
  const sp = spinner(`Generating release notes ${fromRef} → ${toRef}...`).start();

  let repoRoot: string;
  try {
    repoRoot = findRepoRoot(targetDir);
  } catch (e) {
    if (e instanceof NotAGitRepoError) { sp.fail(chalk.red(`Not a git repository`)); throw e; }
    throw e;
  }

  const db = dbPath(repoRoot);
  if (!existsSync(db)) { sp.fail(chalk.red("Not initialized")); throw new Error("Not initialized"); }

  const prisma = getPrisma(db);
  const repo = await getRepository(prisma, repoRoot);
  if (!repo) { sp.fail(chalk.red("Repo not found")); await closePrisma(); throw new Error("Not found"); }

  try {
    const notes = await generateReleaseNotes(prisma, repo.id, fromRef, toRef, repo.name);
    await closePrisma();
    sp.stop();

    const md = renderMarkdown(notes);
    const outPath = join(reportsDir(repoRoot), `release-${toRef}.md`);
    writeFileSync(outPath, md);

    console.log(`\n${chalk.bold(`Release ${notes.version}`)}`);
    console.log(`${chalk.dim(notes.date)}`);
    console.log(`\n${notes.summary}\n`);

    for (const [category, items] of Object.entries(notes.categories)) {
      console.log(chalk.bold(`${category}:`));
      for (const item of items.slice(0, 5)) {
        console.log(`  ${chalk.green("✓")} ${item.slice(0, 80)}`);
      }
      if (items.length > 5) console.log(`  ${chalk.dim(`... and ${items.length - 5} more`)}`);
      console.log();
    }

    console.log(chalk.dim(`Report saved: ${outPath}`));
  } catch (err) {
    sp.fail(chalk.red(`Failed: ${err}`));
    await closePrisma();
    throw err;
  }
}

function renderMarkdown(notes: import("../releasenotes/index.js").ReleaseNote): string {
  let md = `# Release ${notes.version}\n\n`;
  md += `**Date:** ${notes.date}  \n`;
  md += `**Previous:** ${notes.previousVersion}  \n\n`;
  md += `${notes.summary}\n\n---\n\n`;

  for (const [category, items] of Object.entries(notes.categories)) {
    md += `## ${category}\n\n`;
    for (const item of items) {
      md += `- ${item}\n`;
    }
    md += "\n";
  }

  md += `---\n\n_Generated by GitGenius_`;
  return md;
}
