import type { ReportData } from "../index.js";

function bar(count: number, max: number, width = 20): string {
  const filled = Math.round((count / Math.max(max, 1)) * width);
  const bars = "█".repeat(filled) + "░".repeat(Math.max(width - filled, 0));
  return bars;
}

export function renderHtml(data: ReportData): string {
  const maxCommits = Math.max(...data.commitsByMonth.map((m) => m.count), 1);
  const rows = data.commitsByMonth.map((m) =>
    `<tr><td>${m.month}</td><td>${m.count}</td><td><span class="bar" style="width:${(m.count / maxCommits) * 100}%"></span></td></tr>`
  ).join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Report: ${data.repoName}</title>
<style>
  body { font-family: -apple-system, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #333; }
  h1 { border-bottom: 2px solid #eee; padding-bottom: 10px; }
  table { border-collapse: collapse; width: 100%; margin: 16px 0; }
  th, td { text-align: left; padding: 6px 12px; border-bottom: 1px solid #eee; }
  th { background: #f5f5f5; font-weight: 600; }
  .bar { display: inline-block; height: 16px; background: #4f8cf7; border-radius: 3px; min-width: 2px; }
  .stat { display: inline-block; padding: 16px 24px; margin: 8px; background: #f8f9fa; border-radius: 8px; text-align: center; }
  .stat-value { font-size: 28px; font-weight: 700; color: #1a73e8; }
  .stat-label { font-size: 12px; color: #666; }
  .footer { margin-top: 40px; font-size: 12px; color: #999; text-align: center; }
</style></head>
<body>
  <h1>Repository Report: ${data.repoName}</h1>
  <p><strong>Generated:</strong> ${data.generatedAt.split("T")[0]} | <strong>Period:</strong> ${data.dateRange.earliest} → ${data.dateRange.latest}</p>

  <div>
    <div class="stat"><div class="stat-value">${data.totalCommits}</div><div class="stat-label">Commits</div></div>
    <div class="stat"><div class="stat-value">${data.totalFiles}</div><div class="stat-label">Files</div></div>
    <div class="stat"><div class="stat-value">${data.totalAuthors}</div><div class="stat-label">Authors</div></div>
  </div>

  <h2>Commits by Month</h2>
  <table><tr><th>Month</th><th>Count</th><th></th></tr>${rows}</table>

  <h2>Commits by Author</h2>
  <table><tr><th>Author</th><th>Commits</th><th>Insertions</th><th>Deletions</th></tr>
  ${data.commitsByAuthor.map((a) => `<tr><td>${a.author}</td><td>${a.count}</td><td>+${a.insertions}</td><td>-${a.deletions}</td></tr>`).join("\n")}
  </table>

  <h2>Top Files by Churn</h2>
  <table><tr><th>File</th><th>Churn</th><th>Commits</th></tr>
  ${data.filesByChurn.map((f) => `<tr><td>${f.path}</td><td>${f.churn}</td><td>${f.commits}</td></tr>`).join("\n")}
  </table>

  <div class="footer">Generated by GitGenius</div>
</body></html>`;
}
