import type { ReportData } from "../index.js";

export function renderMarkdown(data: ReportData): string {
  let md = `# Repository Report: ${data.repoName}\n\n`;
  md += `**Generated:** ${data.generatedAt.split("T")[0]}  \n`;
  md += `**Period:** ${data.dateRange.earliest} → ${data.dateRange.latest}  \n\n`;
  md += `---\n\n`;

  md += `## Overview\n\n`;
  md += `| Metric | Value |\n|--------|-------|\n`;
  md += `| Total Commits | ${data.totalCommits} |\n`;
  md += `| Total Files | ${data.totalFiles} |\n`;
  md += `| Total Authors | ${data.totalAuthors} |\n\n`;

  md += `## Commits by Author\n\n`;
  md += `| Author | Commits | Insertions | Deletions |\n|--------|---------|------------|-----------|\n`;
  for (const a of data.commitsByAuthor) {
    md += `| ${a.author} | ${a.count} | +${a.insertions} | -${a.deletions} |\n`;
  }

  md += `\n## Commits by Month\n\n`;
  md += `| Month | Commits |\n|-------|---------|\n`;
  for (const m of data.commitsByMonth) {
    const bar = "█".repeat(Math.min(m.count, 40));
    const label = m.month;
    md += `| ${label} | ${String(m.count).padStart(4)} ${bar} |\n`;
  }

  md += `\n## Top Files by Churn\n\n`;
  md += `| File | Churn (+/-) | Commits |\n|------|-------------|---------|\n`;
  for (const f of data.filesByChurn) {
    md += `| ${f.path} | ${f.churn} | ${f.commits} |\n`;
  }

  if (data.categoryBreakdown.length > 0) {
    md += `\n## Analysis Categories\n\n`;
    for (const c of data.categoryBreakdown) {
      md += `- **${c.category}:** ${c.count} chunks\n`;
    }
  }

  md += `\n---\n_Generated by GitGenius_`;
  return md;
}
