import PDFDocument from "pdfkit";
import type { ReportData } from "../index.js";
import { PassThrough } from "node:stream";

export async function renderPdf(data: ReportData): Promise<Buffer> {
  const doc = new PDFDocument({ margin: 50, size: "A4" });
  const stream = new PassThrough();
  const chunks: Buffer[] = [];

  stream.on("data", (chunk: Buffer) => chunks.push(chunk));

  doc.pipe(stream);

  // Title
  doc.fontSize(24).font("Helvetica-Bold").text(`Repository Report: ${data.repoName}`, { align: "center" });
  doc.fontSize(10).font("Helvetica").text(`Generated: ${data.generatedAt.split("T")[0]}`, { align: "center" });
  doc.moveDown(0.5);

  const period = `${data.dateRange.earliest} → ${data.dateRange.latest}`;
  doc.fontSize(10).text(`Period: ${period}`, { align: "center" });
  doc.moveDown(1);

  // Separator
  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#ccc").stroke();
  doc.moveDown(1);

  // Overview stats
  doc.fontSize(16).font("Helvetica-Bold").text("Overview");
  doc.moveDown(0.5);
  doc.fontSize(11).font("Helvetica");
  doc.text(`Total Commits: ${data.totalCommits}`);
  doc.text(`Total Files:   ${data.totalFiles}`);
  doc.text(`Total Authors: ${data.totalAuthors}`);
  doc.moveDown(1);

  // Commits by Author
  doc.fontSize(16).font("Helvetica-Bold").text("Commits by Author");
  doc.moveDown(0.5);
  drawTable(doc, ["Author", "Commits", "Insertions", "Deletions"],
    data.commitsByAuthor.map((a) => [a.author, String(a.count), `+${a.insertions}`, `-${a.deletions}`]));
  doc.moveDown(1);

  // Commits by Month
  doc.fontSize(16).font("Helvetica-Bold").text("Commits by Month");
  doc.moveDown(0.5);
  const maxMonth = Math.max(...data.commitsByMonth.map((m) => m.count), 1);
  for (const m of data.commitsByMonth) {
    const barWidth = (m.count / maxMonth) * 300;
    doc.fontSize(9).font("Helvetica").text(`${m.month}  ${String(m.count).padStart(4)}  `, { continued: true });
    doc.rect(doc.x, doc.y - 4, barWidth, 10).fill("#4f8cf7");
    doc.moveDown(1.2);
  }
  doc.moveDown(1);

  // Top Files by Churn
  doc.fontSize(16).font("Helvetica-Bold").text("Top Files by Churn");
  doc.moveDown(0.5);
  drawTable(doc, ["File", "Churn", "Commits"],
    data.filesByChurn.map((f) => [f.path.length > 40 ? "..." + f.path.slice(-37) : f.path, String(f.churn), String(f.commits)]));

  // Footer
  doc.moveDown(2);
  doc.fontSize(8).fillColor("#999").text("Generated by GitGenius", { align: "center" });

  doc.end();

  return new Promise((resolve) => {
    stream.on("finish", () => resolve(Buffer.concat(chunks)));
  });
}

function drawTable(doc: PDFKit.PDFDocument, headers: string[], rows: string[][]): void {
  const colWidth = 480 / headers.length;
  const startX = 50;

  // Header
  doc.fontSize(10).font("Helvetica-Bold");
  let x = startX;
  for (const h of headers) {
    doc.text(h, x, doc.y, { width: colWidth, align: "left" });
    x += colWidth;
  }
  doc.moveDown(0.5);

  // Rows
  doc.fontSize(9).font("Helvetica");
  for (const row of rows) {
    x = startX;
    const y = doc.y;
    let maxHeight = 0;
    for (let i = 0; i < row.length; i++) {
      doc.text(row[i] ?? "", x, y, { width: colWidth, align: "left" });
      x += colWidth;
    }
    doc.moveDown(0.4);
  }
}
